nav:
- Home: README.md
- User Guide:
  - Getting Started:
    - getting_started/quickstart.md
    - getting_started/installation
  - Examples:
    - examples/README.md
    - Offline Inference:
      - Qwen2.5-Omni: user_guide/examples/offline_inference/qwen2_5_omni.md
      - Qwen3-Omni: user_guide/examples/offline_inference/qwen3_omni.md
      - Text-To-Image: user_guide/examples/offline_inference/text_to_image.md
      - Image-To-Image: user_guide/examples/offline_inference/image_to_image.md
      - Text-To-Video: user_guide/examples/offline_inference/text_to_video.md
    - Online Serving:
      - Qwen2.5-Omni: user_guide/examples/online_serving/qwen2_5_omni.md
      - Qwen3-Omni: user_guide/examples/online_serving/qwen3_omni.md
  - General:
    - usage/*
  - Configuration:
    - configuration/README.md
    - configuration/*
  - Diffusion Acceleration:
    - Overview: user_guide/diffusion_acceleration.md
    - TeaCache: user_guide/teacache.md
    - Cache-DiT: user_guide/cache_dit_acceleration.md
  - Models:
    - models/supported_models.md
- Developer Guide:
  - General:
    - contributing/README.md
    - glob: contributing/*
      flatten_single_child_sections: true
  - Model Implementation:
    - contributing/model/README.md
  - CI: contributing/ci
  - Tests: contributing/tests
  - Design Documents:
    - design/index.md
    - design/architecture_overview.md
    - Feature Design:
      - design/feature/disaggregated_inference.md
      - design/feature/multi_request_streaming.md
      - design/feature/ray_based_execution.md
    - Module Design:
      - design/module/ar_module.md
      - design/module/dit_module.md
      - design/module/entrypoint_module.md
  - Docs Guide: contributing/DOCS_GUIDE.md
- API Reference:
  - api/README.md
  - api/vllm_omni
- CLI Reference: cli
- Community:
  - community/*
  - Slack: https://slack.vllm.ai
  - Blog: https://blog.vllm.ai
  - Forum: https://discuss.vllm.ai
